---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux-Kustomizations
  - auth-secret.yaml
  - runner-envs.yaml
  - nexus-registry.yaml
  - helm-release.yaml
  - runner-deployment.yaml
